//! Mutual funds domain models.
//!
//! This module defines typed representations for the Kite Connect
//! mutual funds (Coin) APIs: orders, SIPs, holdings, and instruments.
//! The HTTP transport layer in `manja-http` and the facade in `manja`
//! re-use these types for JSON and CSV payloads.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Mutual fund order as returned by `/mf/orders` and `/mf/orders/:order_id`.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MfOrder {
    /// Unique order id.
    pub order_id: String,
    /// Exchange generated order id, if available.
    #[serde(default)]
    pub exchange_order_id: Option<String>,
    /// ISIN of the fund.
    pub tradingsymbol: String,
    /// Current status of the order (e.g. `OPEN`, `COMPLETE`, `REJECTED`).
    #[serde(default)]
    pub status: Option<String>,
    /// Textual description of the order's status.
    #[serde(default)]
    pub status_message: Option<String>,
    /// Folio number generated by the AMC for completed purchase orders.
    #[serde(default)]
    pub folio: Option<String>,
    /// Name of the fund.
    pub fund: String,
    /// Timestamp at which the order was registered by the API.
    pub order_timestamp: String,
    /// Date on which the order was registered by the exchange.
    #[serde(default)]
    pub exchange_timestamp: Option<String>,
    /// Exchange settlement ID, if available.
    #[serde(default)]
    pub settlement_id: Option<String>,
    /// Transaction side (BUY or SELL).
    pub transaction_type: String,
    /// Amount placed for purchase of units.
    pub amount: f64,
    /// Number of units allotted or sold.
    pub quantity: f64,
    /// Buy or sell price, when available.
    #[serde(default)]
    pub price: Option<f64>,
    /// Last available NAV price of the fund.
    pub last_price: f64,
    /// Allotted or sold NAV price.
    pub average_price: f64,
    /// Date for which last NAV is available.
    #[serde(default)]
    pub last_price_date: Option<String>,
    /// Order variety (e.g. `regular`, `sip`, `amc_sip`).
    pub variety: String,
    /// Purchase type for BUY orders (e.g. `FRESH`, `ADDITIONAL`).
    #[serde(default)]
    pub purchase_type: Option<String>,
    /// ID of the user that placed the order.
    pub placed_by: String,
    /// Tag sent with the order to identify it.
    #[serde(default)]
    pub tag: Option<String>,
}

/// Mutual fund SIP configuration as returned by `/mf/sips` and `/mf/sips/:id`.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MfSip {
    /// Status of the SIP (e.g. `ACTIVE`, `PAUSED`).
    pub status: String,
    /// SIP registration number, when available.
    #[serde(default)]
    pub sip_reg_num: Option<String>,
    /// Timestamp when the SIP was created.
    pub created: String,
    /// Dividend type (e.g. `growth`, `idcw`).
    pub dividend_type: String,
    /// Amount per instalment.
    pub instalment_amount: f64,
    /// Fund name.
    pub fund: String,
    /// Total number of instalments; `-1` for perpetual.
    pub instalments: i64,
    /// Date of the next instalment.
    pub next_instalment: String,
    /// Transaction side (currently `BUY`).
    pub transaction_type: String,
    /// Optional trigger price.
    pub trigger_price: f64,
    /// Step-up configuration keyed by `dd-mm`.
    #[serde(default)]
    pub step_up: HashMap<String, i64>,
    /// ISIN of the fund.
    pub tradingsymbol: String,
    /// Optional client tag for this SIP.
    #[serde(default)]
    pub tag: Option<String>,
    /// Frequency of instalments (e.g. `weekly`, `monthly`, `quarterly`).
    pub frequency: String,
    /// Timestamp of the last instalment.
    pub last_instalment: String,
    /// Remaining instalments; `-1` for perpetual.
    pub pending_instalments: i64,
    /// Day of instalment for monthly/quarterly SIPs.
    pub instalment_day: i64,
    /// SIP type (e.g. `sip`, `amc_sip`).
    pub sip_type: String,
    /// Number of completed instalments.
    pub completed_instalments: i64,
    /// Unique SIP id.
    pub sip_id: String,
    /// Source of funds for this SIP, when available (e.g. `pool`).
    #[serde(default)]
    pub fund_source: Option<String>,
}

/// Mutual fund holding as returned by `/mf/holdings`.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MfHolding {
    /// Folio number generated by the AMC.
    #[serde(default)]
    pub folio: Option<String>,
    /// Allotted NAV price for a completed BUY or SELL.
    pub average_price: f64,
    /// Last available NAV price.
    pub last_price: f64,
    /// Date for which last NAV is available.
    pub last_price_date: String,
    /// Quantity pledged.
    pub pledged_quantity: f64,
    /// Name of the fund.
    pub fund: String,
    /// ISIN of the fund.
    pub tradingsymbol: String,
    /// Net returns of the holding.
    pub pnl: f64,
    /// Net returns percentage, when provided by the API.
    #[serde(default)]
    pub pnl_percentage: Option<f64>,
    /// Quantity available in the client's holding for this ISIN.
    pub quantity: f64,
}

/// Mutual fund instrument row from `/mf/instruments` CSV dump.
#[derive(Debug, Deserialize, Clone)]
pub struct MfInstrument {
    /// ISIN of the fund.
    pub tradingsymbol: String,
    /// AMC code as per the exchange.
    pub amc: String,
    /// Fund name.
    pub name: String,
    /// `0` or `1` as string/integer indicating whether purchase is allowed.
    pub purchase_allowed: i32,
    /// `0` or `1` as string/integer indicating whether redemption is allowed.
    pub redemption_allowed: i32,
    /// Minimum purchase amount for the first BUY.
    pub minimum_purchase_amount: f64,
    /// BUY amount should be a multiple of this value.
    pub purchase_amount_multiplier: f64,
    /// Minimum additional BUY amount.
    pub minimum_additional_purchase_amount: f64,
    /// Minimum SELL quantity.
    pub minimum_redemption_quantity: f64,
    /// SELL quantity multiple.
    pub redemption_quantity_multiplier: f64,
    /// Dividend type (`growth` or `payout`).
    pub dividend_type: String,
    /// Scheme type (`equity`, `debt`, `elss`, etc.).
    pub scheme_type: String,
    /// Plan (`direct` or `regular`).
    pub plan: String,
    /// Settlement type of the fund (e.g. `T1`, `T3`).
    pub settlement_type: String,
    /// Last available NAV price of the fund.
    pub last_price: f64,
    /// Date for which last NAV is available.
    pub last_price_date: String,
}

